=== trabajoJorge/Web-PHP---Mobile-Sales/xml/solicitudes.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT solicitudes (solicitud)*>
<!ATTLIST solicitudes ult_id IDREF #REQUIRED>

<!ELEMENT solicitud (movil_id, usuario_id, fecha_solicitud)>
<!ATTLIST solicitud id ID #REQUIRED>
<!ELEMENT movil_id (#PCDATA)>
<!ELEMENT usuario_id (#PCDATA)>
<!ELEMENT fecha_solicitud (#PCDATA)>

=== trabajoJorge/Web-PHP---Mobile-Sales/xml/solicitudes.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE solicitudes SYSTEM "solicitudes.dtd">
<solicitudes ult_id="s_6">
    <solicitud id="s_1">
        <movil_id>6</movil_id>
        <usuario_id>u_1</usuario_id>
        <fecha_solicitud>13-12-2020</fecha_solicitud>
    </solicitud>
    <solicitud id="s_2">
        <movil_id>8</movil_id>
        <usuario_id>u_4</usuario_id>
        <fecha_solicitud>11-12-2020</fecha_solicitud>
    </solicitud>
    <solicitud id="s_3">
        <movil_id>6</movil_id>
        <usuario_id>u_2</usuario_id>
        <fecha_solicitud>12-12-2020</fecha_solicitud>
    </solicitud>
    <solicitud id="s_4">
        <movil_id>7</movil_id>
        <usuario_id>u_3</usuario_id>
        <fecha_solicitud>13-12-2020</fecha_solicitud>
    </solicitud>
    <solicitud id="s_5">
        <movil_id>8</movil_id>
        <usuario_id>u_2</usuario_id>
        <fecha_solicitud>13-12-2020</fecha_solicitud>
    </solicitud>
    <solicitud id="s_6">
        <movil_id>6</movil_id>
        <usuario_id>u_3</usuario_id>
        <fecha_solicitud>13-12-2020</fecha_solicitud>
    </solicitud>
</solicitudes>
